### ISSUE TITLE
Missing info.csv file on task 1

### ISSUE THREAD

**Issue by Tinglok** [l3das/L3DAS23#1]
Thanks so much for contributing to this dataset!

When downloading the dataset, I am getting the following error:
Traceback (most recent call last):
  File "download_dataset.py", line 107, in <module>
    merge_train360(part1_path, part2_path)
  File "download_dataset.py", line 82, in merge_train360
    merge_csv(info_1_path, info_2_path, info_2_path)
  File "download_dataset.py", line 36, in merge_csv
    df = pd.concat(map(pd.read_csv, [path1, path2]),
FileNotFoundError: [Errno 2] No such file or directory: './DATASETS/L3DAS23_Task1_train_360_part2/L3DAS23_Task1_train_360_part2/info.csv'

I have checked the dataset at [Kaggle](https://www.kaggle.com/datasets/l3dasteam/l3das23-task1) and turns out there's no `info.csv` file in the `L3DAS23_Task1_train_360_part2` directory. Could someone please upload this .csv file to Kaggle?

**Comment by chrismarinoni** [comment]
Hi @Tinglok,

thanks for spotting this error. In the version of the dataset we published on Kaggle, the info labels are already merged into the info.csv file included in part 1, so no additional files are needed. We just updated the code and run a quick check, let us know if it works fine now.

Thanks again for your feedback!
